[package]
name = "oca"
version = "0.7.4"
edition = "2021"
authors = ["Human Colossus Community <contact@humancolossus.org>"]
license = "EUPL-1.2"
readme = "README.md"
description = "Tool to deal with OCA ecosystem"
include = ["src/**", "config/semantic.overlayfile", "Cargo.toml", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "oca"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
clap = { version = "4.5.55", features = ["derive"] }
log = "0.4.29"
oca-store = { version = "2.0.0-rc.6", features = ["local-references"] }
oca-sdk-rs = { version = "2.0.0-rc.5" }
oca-data-entry = { version = "0.2.4", features = ["writers-csv", "writers-xlsx"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.13", features = ["json", "blocking"] }
toml = "0.9"
isolang = { version = "2.4.0", features = ["serde"] }
walkdir = "2.5"
indexmap = "2.13.0"
thiserror = "2.0.18"
recursion = "0.5.4"
itertools = "0.14.0"
serde_yaml = "0.9.34"
regex = "1.12.2"
ratatui = "0.30.0"
crossterm = "0.29.0"
anyhow = "1.0.100"
petgraph = "0.8.3"
tui-tree-widget = "0.24.0"
throbber-widgets-tui = "0.10.0"
tui-widget-list = "0.15.0"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
lazy_static = "1.5.0"
color-eyre = "0.6.5"
url = "2.5.8"
common-path = "1.0.0"
sha2 = "0.10"
base64 = "0.22"
kv = {version = "0.24.0", features = ["json-value"]}

[dev-dependencies]
tempdir = "0.3.7"

[dependencies.rusqlite]
version = "0.37.0"
features = ["bundled"]

[profile.release]
debug = true
